spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sai
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
